### ISSUE TITLE
Icon for UKUI?

### ISSUE THREAD

**Issue by ucSec** [sparkylinux/sparky-desktop#5]
![](https://avatars1.githubusercontent.com/u/25052540?s=200&v=4)
https://github.com/ukui/

**Comment by pavroo** [comment]
Can you provide a link to the icon license, please?

**Comment by ucSec** [comment]
I asked in their forum, the super moderator said it's under GPL3, but I'm not sure about it...

then I found a startmenu.svg in their repo, under [LGPL-2.1 License ](https://github.com/ukui/ukui-panel/blob/master/COPYING)
https://github.com/ukui/ukui-panel/blob/master/panel/img/startmenu.svg
![](https://github.com/ukui/ukui-panel/raw/master/panel/img/startmenu.svg)

**Comment by pavroo** [comment]
ok, found it:
Files: panel/img/*
       panel/customstyle.cpp
       panel/customstyle.h
Copyright: 2019, Tianjin KYLIN Information Technology Co., Ltd.
License: LGPL-2.1+

thanks, will add it to aptus.
