### ISSUE TITLE
There is no '/usr/share/sparky-desktop-data/lxqt/skel/.config/openbox/rc.xml'

### ISSUE THREAD

**Issue by ucSec** [sparkylinux/sparky-desktop#6]
When I tried to install LXQt with sparky-desktop, it shows:
```
xingjiapeng@xingjiapeng-pc:~$ sudo sparky-desktop lxqt
cp: 无法获取'/usr/share/sparky-desktop-data/lxqt/skel/.config/openbox/rc.xml' 的文件状态(stat): 没有那个文件或目录
```
https://github.com/sparkylinux/sparky-desktop/blob/b1cf0980b84196e65aaab9d2caf0b1c31b640530/bin/sparky-desktop#L1487
However, I found there is no "lxqt/skel/.config/openbox/rc.xml" in sparky-desktop-data.

**Comment by pavroo** [comment]
Fixed, thanks.
